#============================================
#PROD - SERVIDOR
#============================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=PeopleSecretKeyMuyLargaParaQueSeaSegura2024!!

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false