# ============================================
# DEV - LOCAL
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:15434/postgres
spring.datasource.username=postgres
spring.datasource.password=People

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=people